ValueSet: ValueSetHypertensiveDisordersOfPregnancyICD10
Id: hypertensive-disorders-pregnancy-ICD
Title: "ValueSet – Hypertensive Disorders of Pregnancy ICD"
Description: "This value set includes terms related to hypertensive disorders of pregnancy which include pre-existing hypertension, chronic hypertension, hypertensive chronic kidney disease, essential hypertension, hypertension diagnosed during the course of pregnancy and diagnoses of pre-eclampsia and eclampsia."
* ^meta.versionId = "7"
* ^meta.lastUpdated = "2022-03-01T17:34:08.569+00:00"
* ^meta.source = "#SooQ5o4wacYGudiF"
* ^status = #draft
* ^experimental = false
* ^copyright = "ICD-10-cm"
* $icd10cm#O10.01 "Pre-existing essential hypertension complicating pregnancy,"
* $icd10cm#O10.011 "Pre-existing essential hypertension complicating pregnancy, first trimester"
* $icd10cm#O10.012 "Pre-existing essential hypertension complicating pregnancy, second trimester"
* $icd10cm#O10.013 "Pre-existing essential hypertension complicating pregnancy, third trimester"
* $icd10cm#O10.019 "Pre-existing essential hypertension complicating pregnancy, unspecified trimester"
* $icd10cm#O10.02 "Pre-existing essential hypertension complicating childbirth"
* $icd10cm#O10.03 "Pre-existing essential hypertension complicating the puerperium"
* $icd10cm#O10.11 "Pre-existing hypertensive heart disease complicating pregnancy"
* $icd10cm#O10.111 "Pre-existing hypertensive heart disease complicating pregnancy, first trimester"
* $icd10cm#O10.112 "Pre-existing hypertensive heart disease complicating pregnancy, second trimester"
* $icd10cm#O10.113 "Pre-existing hypertensive heart disease complicating pregnancy, third trimester"
* $icd10cm#O10.119 "Pre-existing hypertensive heart disease complicating pregnancy, unspecified trimester"
* $icd10cm#O10.12 "Pre-existing hypertensive heart disease complicating childbirth"
* $icd10cm#O10.13 "Pre-existing hypertensive heart disease complicating the puerperium"
* $icd10cm#O10.211 "Pre-existing hypertensive chronic kidney disease complicating pregnancy, first trimester"
* $icd10cm#O10.212 "Pre-existing hypertensive chronic kidney disease complicating pregnancy, second trimester"
* $icd10cm#O10.213 "Pre-existing hypertensive chronic kidney disease complicating pregnancy, third trimester"
* $icd10cm#O10.219 "Pre-existing hypertensive chronic kidney disease complicating pregnancy, unspecified trimester"
* $icd10cm#O10.22 "Pre-existing hypertensive chronic kidney disease complicating childbirth"
* $icd10cm#O10.23 "Pre-existing hypertensive chronic kidney disease complicating the puerperium"
* $icd10cm#O10.311 "Pre-existing hypertensive heart and chronic kidney disease complicating pregnancy, first trimester"
* $icd10cm#O10.312 "Pre-existing hypertensive heart and chronic kidney disease complicating pregnancy, second trimester"
* $icd10cm#O10.313 "Pre-existing hypertensive heart and chronic kidney disease complicating pregnancy, third trimester"
* $icd10cm#O10.319 "Pre-existing hypertensive heart and chronic kidney disease complicating pregnancy, unspecified trimester"
* $icd10cm#O10.32 "Pre-existing hypertensive heart and chronic kidney disease complicating childbirth"
* $icd10cm#O10.33 "Pre-existing hypertensive heart and chronic kidney disease complicating the puerperium"
* $icd10cm#O10.41 "Pre-existing secondary hypertension complicating pregnancy"
* $icd10cm#O10.411 "Pre-existing secondary hypertension complicating pregnancy, first trimester"
* $icd10cm#O10.412 "Pre-existing secondary hypertension complicating pregnancy, second trimester"
* $icd10cm#O10.413 "Pre-existing secondary hypertension complicating pregnancy, third trimester"
* $icd10cm#O10.419 "Pre-existing secondary hypertension complicating pregnancy, unspecified trimester"
* $icd10cm#O10.42 "Pre-existing secondary hypertension complicating childbirth"
* $icd10cm#O10.43 "Pre-existing secondary hypertension complicating the puerperium"
* $icd10cm#O10.91 "Unspecified pre-existing hypertension complicating pregnancy"
* $icd10cm#O10.911 "Unspecified pre-existing hypertension complicating pregnancy, first trimester"
* $icd10cm#O10.912 "Unspecified pre-existing hypertension complicating pregnancy, second trimester"
* $icd10cm#O10.913 "Unspecified pre-existing hypertension complicating pregnancy, third trimester"
* $icd10cm#O10.919 "Unspecified pre-existing hypertension complicating pregnancy, unspecified trimester"
* $icd10cm#O10.92 "Unspecified pre-existing hypertension complicating childbirth"
* $icd10cm#O10.93 "Unspecified pre-existing hypertension complicating the puerperium"
* $icd10cm#O11 "Pre-existing hypertension with pre-eclampsia"
* $icd10cm#O11.1 "Pre-existing hypertension with pre-eclampsia, first trimester"
* $icd10cm#O11.2 "Pre-existing hypertension with pre-eclampsia, second trimester"
* $icd10cm#O11.3 "Pre-existing hypertension with pre-eclampsia, third trimester"
* $icd10cm#O11.4 "Pre-existing hypertension with pre-eclampsia, complicating childbirth"
* $icd10cm#O11.5 "Pre-existing hypertension with pre-eclampsia, complicating the puerperium"
* $icd10cm#O11.9 "Pre-existing hypertension with pre-eclampsia, unspecified trimester"
* $icd10cm#O13 "Gestational [pregnancy-induced] hypertension without significant proteinuria"
* $icd10cm#O13.1 "Gestational [pregnancy-induced] hypertension without significant proteinuria, first trimester"
* $icd10cm#O13.2 "Gestational [pregnancy-induced] hypertension without significant proteinuria, second trimester"
* $icd10cm#O13.3 "Gestational [pregnancy-induced] hypertension without significant proteinuria, third trimester"
* $icd10cm#O13.4 "Gestational [pregnancy-induced] hypertension without significant proteinuria, complicating childbirth"
* $icd10cm#O13.5 "Gestational [pregnancy-induced] hypertension without significant proteinuria, complicating the puerperium"
* $icd10cm#O13.9 "Gestational [pregnancy-induced] hypertension without significant proteinuria, unspecified trimester"
* $icd10cm#O14.00 "Mild to moderate pre-eclampsia, unspecified trimester"
* $icd10cm#O14.02 "Mild to moderate pre-eclampsia, second trimester"
* $icd10cm#O14.03 "Mild to moderate pre-eclampsia, third trimester"
* $icd10cm#O14.04 "Mild to moderate pre-eclampsia, complicating childbirth"
* $icd10cm#O14.05 "Mild to moderate pre-eclampsia, complicating the puerperium"
* $icd10cm#O14.1 "Severe pre-eclampsia"
* $icd10cm#O14.10 "Severe pre-eclampsia, unspecified trimester"
* $icd10cm#O14.12 "Severe pre-eclampsia, second trimester"
* $icd10cm#O14.13 "Severe pre-eclampsia, third trimester"
* $icd10cm#O14.14 "Severe pre-eclampsia complicating childbirth"
* $icd10cm#O14.15 "Severe pre-eclampsia, complicating the puerperium"
* $icd10cm#O14.2 "HELLP syndrome"
* $icd10cm#O14.20 "HELLP syndrome (HELLP), unspecified trimester"
* $icd10cm#O14.22 "HELLP syndrome (HELLP), second trimester"
* $icd10cm#O14.23 "HELLP syndrome (HELLP), third trimester"
* $icd10cm#O14.24 "HELLP syndrome, complicating childbirth"
* $icd10cm#O14.25 "HELLP syndrome, complicating the puerperium"
* $icd10cm#O14.9 "Unspecified pre-eclampsia"
* $icd10cm#O14.90 "Unspecified pre-eclampsia, unspecified trimester"
* $icd10cm#O14.92 "Unspecified pre-eclampsia, second trimester"
* $icd10cm#O14.93 "Unspecified pre-eclampsia, third trimester"
* $icd10cm#O14.94 "Unspecified pre-eclampsia, complicating childbirth"
* $icd10cm#O14.95 "Unspecified pre-eclampsia, complicating the puerperium"
* $icd10cm#O15 "Eclampsia"
* $icd10cm#O15.0 "Eclampsia complicating pregnancy"
* $icd10cm#O15.00 "Eclampsia complicating pregnancy, unspecified trimester"
* $icd10cm#O15.02 "Eclampsia complicating pregnancy, second trimester"
* $icd10cm#O15.03 "Eclampsia complicating pregnancy, third trimester"
* $icd10cm#O15.1 "Eclampsia complicating labor"
* $icd10cm#O15.2 "Eclampsia complicating the puerperium"
* $icd10cm#O15.9 "Eclampsia, unspecified as to time period"
* $icd10cm#O16 "Unspecified maternal hypertension"
* $icd10cm#O16.1 "Unspecified maternal hypertension, first trimester"
* $icd10cm#O16.2 "Unspecified maternal hypertension, second trimester"
* $icd10cm#O16.3 "Unspecified maternal hypertension, third trimester"
* $icd10cm#O16.4 "Unspecified maternal hypertension, complicating childbirth"
* $icd10cm#O16.5 "Unspecified maternal hypertension, complicating the puerperium"
* $icd10cm#O16.9 "Unspecified maternal hypertension, unspecified trimester"