ValueSet: ValueSetHypertensiveDisordersOfPregnancySNOMED
Id: hypertensive-disorders-pregnancy-SNOMED
Title: "ValueSet – Hypertensive Disorders of Pregnancy SNOMED CT"
Description: "This value set includes terms related to hypertensive disorders of pregnancy which include pre-existing hypertension, chronic hypertension, hypertensive chronic kidney disease, essential hypertension, hypertension diagnosed during the course of pregnancy and diagnoses of pre-eclampsia and eclampsia."
* ^meta.versionId = "6"
* ^meta.lastUpdated = "2022-03-15T17:41:46.812+00:00"
* ^meta.source = "#nPwnjlaSBKKCKQvu"
* ^status = #draft
* ^experimental = false
* ^copyright = "This value set includes content from SNOMED CT, which is copyright © 2002+ International Health Terminology Standards Development Organisation (IHTSDO), and distributed by agreement between IHTSDO and HL7. Implementer use of SNOMED CT is not covered by this agreement"
* $sct#1474004 "Hypertensive heart AND renal disease complicating AND/OR reason for care during childbirth (disorder)"
* $sct#8218002 "Chronic hypertension complicating AND/OR reason for care during childbirth (disorder)"
* $sct#8762007 "Chronic hypertension in obstetric context (disorder)"
* $sct#9901000 "Essential hypertension complicating AND/OR reason for care during puerperium (disorder)"
* $sct#10562009 "Malignant hypertension complicating AND/OR reason for care during childbirth (disorder)"
* $sct#15938005 "Eclampsia (disorder)"
* $sct#18416000 "Essential hypertension complicating AND/OR reason for care during childbirth (disorder)"
* $sct#20753005 "Hypertensive heart disease complicating AND/OR reason for care during pregnancy (disorder)"
* $sct#22966008 "Hypertensive heart AND renal disease complicating AND/OR reason for care during pregnancy (disorder)"
* $sct#23717007 "Benign essential hypertension complicating AND/OR reason for care during pregnancy (disorder)"
* $sct#23786008 "Malignant hypertension complicating AND/OR reason for care during puerperium (disorder)"
* $sct#24042004 "Chronic hypertension complicating AND/OR reason for care during puerperium (disorder)"
* $sct#26078007 "Hypertension secondary to renal disease complicating AND/OR reason for care during childbirth (disorder)"
* $sct#29259002 "Malignant hypertension complicating AND/OR reason for care during pregnancy (disorder)"
* $sct#34273003 "Hypertensive heart disease complicating AND/OR reason for care during puerperium (disorder)"
* $sct#37618003 "Chronic hypertension complicating AND/OR reason for care during pregnancy (disorder)"
* $sct#38341003 "Hypertensive disorder, systemic arterial (disorder)"
* $sct#39727004 "Hypertension secondary to renal disease complicating AND/OR reason for care during puerperium (disorder)"
* $sct#41114007 "Mild pre-eclampsia (disorder)"
* $sct#46764007 "Severe pre-eclampsia (disorder)"
* $sct#48146000 "Diastolic hypertension (disorder)"
* $sct#48194001 "Pregnancy-induced hypertension (disorder)"
* $sct#48552006 "Hypertension secondary to renal disease complicating AND/OR reason for care during pregnancy (disorder)"
* $sct#49102001 "Hypertensive heart AND renal disease in obstetric context (disorder)"
* $sct#49171007 "Hypertensive renal disease complicating AND/OR reason for care during childbirth (disorder)"
* $sct#56218007 "Systolic hypertension (disorder)"
* $sct#57873008 "Hypertensive renal disease complicating AND/OR reason for care during puerperium (disorder)"
* $sct#59720008 "Sustained diastolic hypertension (disorder)"
* $sct#59733002 "Hypertensive heart disease complicating AND/OR reason for care during childbirth (disorder)"
* $sct#63287004 "Benign essential hypertension in obstetric context (disorder)"
* $sct#65402008 "Pre-existing hypertension complicating AND/OR reason for care during pregnancy (disorder)"
* $sct#66709007 "Hypertensive renal disease complicating AND/OR reason for care during pregnancy (disorder)"
* $sct#69909000 "Eclampsia added to pre-existing hypertension (disorder)"
* $sct#71874008 "Benign essential hypertension complicating AND/OR reason for care during childbirth (disorder)"
* $sct#72022006 "Essential hypertension in obstetric context (disorder)"
* $sct#73030000 "Hypertensive renal disease in obstetric context (disorder)"
* $sct#74451002 "Secondary diastolic hypertension (disorder)"
* $sct#78808002 "Essential hypertension complicating AND/OR reason for care during pregnancy (disorder)"
* $sct#79355007 "Hypertensive heart disease in obstetric context (disorder)"
* $sct#81626002 "Malignant hypertension in obstetric context (disorder)"
* $sct#86041002 "Pre-existing hypertension in obstetric context (disorder)"
* $sct#106005003 "Hypertension AND/OR vomiting complicating pregnancy childbirth AND/OR puerperium (disorder)"
* $sct#111438007 "Hypertension secondary to renal disease in obstetric context (disorder)"
* $sct#198942000 "Benign essential hypertension complicating pregnancy, childbirth and the puerperium (disorder)"
* $sct#198944004 "Benign essential hypertension complicating pregnancy, childbirth and the puerperium - delivered (disorder)"
* $sct#198945003 "Benign essential hypertension complicating pregnancy, childbirth and the puerperium - delivered with postnatal complication (disorder)"
* $sct#198946002 "Benign essential hypertension complicating pregnancy, childbirth and the puerperium - not delivered (disorder)"
* $sct#198947006 "Benign essential hypertension complicating pregnancy, childbirth and the puerperium with postnatal complication (disorder)"
* $sct#198949009 "Renal hypertension complicating pregnancy, childbirth and the puerperium (disorder)"
* $sct#198951008 "Renal hypertension complicating pregnancy, childbirth and the puerperium - delivered (disorder)"
* $sct#198952001 "Renal hypertension complicating pregnancy, childbirth and the puerperium - delivered with postnatal complication (disorder)"
* $sct#198953006 "Renal hypertension complicating pregnancy, childbirth and the puerperium - not delivered (disorder)"
* $sct#198965005 "Transient hypertension of pregnancy - delivered (disorder)"
* $sct#198966006 "Transient hypertension of pregnancy - delivered with postnatal complication (disorder)"
* $sct#198967002 "Transient hypertension of pregnancy - not delivered (disorder)"
* $sct#198968007 "Transient hypertension of pregnancy with postnatal complication (disorder)"
* $sct#198983002 "Severe pre-eclampsia - delivered (disorder)"
* $sct#198984008 "Severe pre-eclampsia - delivered with postnatal complication (disorder)"
* $sct#198985009 "Severe pre-eclampsia - not delivered (disorder)"
* $sct#198986005 "Severe pre-eclampsia with postnatal complication (disorder)"
* $sct#198990007 "Eclampsia - delivered (disorder)"
* $sct#198991006 "Eclampsia - delivered with postnatal complication (disorder)"
* $sct#198992004 "Eclampsia in pregnancy (disorder)"
* $sct#198993009 "Eclampsia with postnatal complication (disorder)"
* $sct#198997005 "Pre-eclampsia or eclampsia with pre-existing hypertension (disorder)"
* $sct#198999008 "Pre-eclampsia or eclampsia with pre-existing hypertension - delivered (disorder)"
* $sct#199000005 "Pre-eclampsia or eclampsia with pre-existing hypertension - delivered with postnatal complication (disorder)"
* $sct#199002002 "Pre-eclampsia or eclampsia with pre-existing hypertension - not delivered (disorder)"
* $sct#199003007 "Pre-eclampsia or eclampsia with pre-existing hypertension with postnatal complication (disorder)"
* $sct#199006004 "Pre-existing hypertensive heart disease complicating pregnancy, childbirth and the puerperium (disorder)"
* $sct#237279007 "Transient hypertension of pregnancy (disorder)"
* $sct#237281009 "Moderate proteinuric hypertension of pregnancy (disorder)"
* $sct#237282002 "Impending eclampsia (disorder)"
* $sct#237283007 "Eclampsia in labor (disorder)"
* $sct#288250001 "Maternal hypertension (disorder)"
* $sct#303063000 "Eclampsia in puerperium (disorder)"
* $sct#307632004 "Non-proteinuric hypertension of pregnancy (disorder)"
* $sct#367390009 "Hypertension in the obstetric context (disorder)"
* $sct#398254007 "Pre-eclampsia (disorder)"
* $sct#429457004 "Systolic essential hypertension (disorder)"
* $sct#698638005 "Pregnancy induced hypertension with pulmonary edema (disorder)"
* $sct#698640000 "Hypertension in the puerperium with pulmonary edema (disorder)"
* $sct#762463000 "Diastolic hypertension co-occurrent with systolic hypertension (disorder)"
* $sct#765182005 "Pre-eclampsia in puerperium (disorder)"
* $sct#541000119105 "Hypertension complicating pregnancy, childbirth and the puerperium, antepartum (disorder)"
* $sct#40511000119107 "Postpartum pre-existing essential hypertension (disorder)"
* $sct#82771000119102 "Hypertension complicating pregnancy (disorder)"
* $sct#118781000119108 "Pre-existing hypertensive chronic kidney disease in mother complicating pregnancy (disorder)"
* $sct#10752641000119102 "Eclampsia with pre-existing hypertension in childbirth (disorder)"
* $sct#10757481000119107 "Pre-existing hypertensive heart and chronic kidney disease in mother complicating pregnancy (disorder)"
* $sct#10759031000119106 "Pre-existing hypertensive heart disease in mother complicating pregnancy (disorder)"