Instance: MaternalBehavioralHealth-Cohort-of-Library
InstanceOf: Library
Title: "Library for Behavioral Health Issues during Pregnancy"
Description: "Library for Behavioral Health Issues during Pregnancy. The cql logic for the calculation of mother Patients who are expected to be found within the Behavioral Health Issues during Pregnancy cohort is contained."
Usage: #definition
* id = "MaternalBehavioralHealthCohort"
* meta.versionId = "1"
* meta.lastUpdated = "2026-02-16T00:00:00Z"
* extension.url = "http://hl7.org/fhir/us/cqfmeasures/StructureDefinition/cqfm-softwaresystem"
* extension.valueReference = Reference(cqf-tooling)
* url = "http://fhir.org/guides/cqf/Library/MaternalBehavioralHealthCohort"
* version = "0.0.1"
* name = "MaternalBehavioralHealthCohort"
* status = #draft
* experimental = false
* type = $library-type#logic-library "Logic Library"
* relatedArtifact[+].type = #depends-on
* relatedArtifact[=].display = "Code system SNOMEDCT"
* relatedArtifact[=].resource = "http://snomed.info/sct"
* relatedArtifact[+].type = #depends-on
* relatedArtifact[=].display = "Code system LOINC"
* relatedArtifact[=].resource = "http://loinc.org"
* relatedArtifact[+].type = #depends-on
* relatedArtifact[=].display = "FHIR model information"
* relatedArtifact[=].resource = "http://fhir.org/guides/cqf/common/Library/FHIR-ModelInfo|4.0.1"
* relatedArtifact[+].type = #depends-on
* relatedArtifact[=].display = "Library FHIRHelpers"
* relatedArtifact[=].resource = "http://fhir.org/guides/cqf/Library/FHIRHelpers|4.0.1"
* relatedArtifact[+].type = #depends-on
* relatedArtifact[=].display = "Library Global"
* relatedArtifact[=].resource = "http://fhir.org/guides/cqf/Library/MATGlobalCommonFunctionsFHIR4|6.1.000"
* parameter[0].name = #"Measurement Period"
* parameter[=].use = #in
* parameter[=].min = 0
* parameter[=].max = "1"
* parameter[=].type = #Period
* parameter[+].name = #"SDE Patient"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Patient
* parameter[+].name = #"SDE Insurance Coverage"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Coverage
* parameter[+].name = #"SDE Behavioral Health Disorders During or After Pregnancy"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE Behavioral Health Medications During or After Pregnancy"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #MedicationRequest
* parameter[+].name = #"SDE Hypertension During Pregnancy"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE Preeclampsia"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE Eclampsia"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE Gestational Diabetes"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE Postpartum Hypertension"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE Suicide Ideation"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE Suicide Attempt"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE Stillbirth"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE Pregnancy Loss"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE Labor and Delivery Complications"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE Antenatal Encounter"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Encounter
* parameter[+].name = #"SDE Emergency Department Encounter"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Encounter
* parameter[+].name = #"SDE Psychiatric Hospitalization"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Encounter
* parameter[+].name = #"SDE Postpartum Encounter"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Encounter
* parameter[+].name = #"SDE Delivery Date"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "1"
* parameter[=].type = #dateTime
* parameter[+].name = #"SDE Antenatal Body Weight"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Observation
* parameter[+].name = #"SDE Edinburgh Postnatal Depression Scale (EPDS) Screening Scores"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Observation
* parameter[+].name = #"SDE GAD-7 Anxiety Screening Scores"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Observation
* parameter[+].name = #"SDE MDQ Screening Scores"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Observation
* parameter[+].name = #"SDE PHQ9 Screening Scores"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Observation
* parameter[+].name = #"SDE PHQ2 Screening Scores"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Observation
* parameter[+].name = #"SDE Observation Serum Level of Mood Stabilizers"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Observation
* parameter[+].name = #"SDE Order for Psychotherapy"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #ServiceRequest
* parameter[+].name = #"SDE Psychotherapy Procedure"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Procedure
* parameter[+].name = #"SDE Gestational Age at Delivery"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "1"
* parameter[=].type = #Observation
* parameter[+].name = #"SDE Infant Patient"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "1"
* parameter[=].type = #Patient
* parameter[+].name = #"SDE Infant Body Weight at Birth"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "1"
* parameter[=].type = #Observation
* parameter[+].name = #"SDE Diagnosis of Congenital Anomalies"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE Diagnosis of Developmental Delays"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Condition
* parameter[+].name = #"SDE NICU Admission"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Encounter
* parameter[+].name = #"SDE Initial Well Child Visit"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "1"
* parameter[=].type = #Encounter
* parameter[+].name = #"SDE PHQ9 Self-Harm Item"
* parameter[=].use = #out
* parameter[=].min = 0
* parameter[=].max = "*"
* parameter[=].type = #Observation
* content[0].contentType = #text/cql
* content[=].data = "bGlicmFyeSBNYXRlcm5hbEJlaGF2aW9yYWxIZWFsdGggLy8gdmVyc2lvbiAnMC4wLjEnCgp1c2luZyBGSElSIHZlcnNpb24gJzQuMC4xJwoKaW5jbHVkZSBGSElSSGVscGVycyB2ZXJzaW9uICc0LjAuMScgY2FsbGVkIEZISVJIZWxwZXJzCmluY2x1ZGUgTUFUR2xvYmFsQ29tbW9uRnVuY3Rpb25zRkhJUjQgdmVyc2lvbiAnNi4xLjAwMCcgY2FsbGVkIEdsb2JhbAoKY29kZXN5c3RlbSAiU05PTUVEQ1QiOiAnaHR0cDovL3Nub21lZC5pbmZvL3NjdCcKY29kZXN5c3RlbSAiTE9JTkMiOiAnaHR0cDovL2xvaW5jLm9yZycKY29kZXN5c3RlbSAiT2JzZXJ2YXRpb24gQ2F0ZWdvcnkiOiAnaHR0cDovL3Rlcm1pbm9sb2d5LmhsNy5vcmcvQ29kZVN5c3RlbS9vYnNlcnZhdGlvbi1jYXRlZ29yeScKY29kZXN5c3RlbSAiUmVsYXRpb25zaGlwVHlwZSI6ICdodHRwOi8vdGVybWlub2xvZ3kuaGw3Lm9yZy9Db2RlU3lzdGVtL3YzLVJvbGVDb2RlJwpjb2Rlc3lzdGVtICJFbmNvdW50ZXIgQ2xhc3MiOiAnCWh0dHA6Ly90ZXJtaW5vbG9neS5obDcub3JnL1ZhbHVlU2V0L3YzLUFjdEVuY291bnRlckNvZGUnCmNvZGVzeXN0ZW0gIkNvbmRpdGlvbiBWZXJpZmljYXRpb24gU3RhdHVzIjogJ2h0dHA6Ly90ZXJtaW5vbG9neS5obDcub3JnL0NvZGVTeXN0ZW0vY29uZGl0aW9uLXZlci1zdGF0dXMnCgp2YWx1ZXNldCAiQW54aWV0eSI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjExOTYuMTkzMycKdmFsdWVzZXQgIkJpcG9sYXIgRGlzb3JkZXIiOiAnaHR0cDovL2N0cy5ubG0ubmloLmdvdi9maGlyL1ZhbHVlU2V0LzIuMTYuODQwLjEuMTEzNzYyLjEuNC4xMTk2LjMzMDEnCnZhbHVlc2V0ICJEZXByZXNzaW9uIjogJ2h0dHA6Ly9jdHMubmxtLm5paC5nb3YvZmhpci9WYWx1ZVNldC8yLjE2Ljg0MC4xLjExMzc2Mi4xLjQuMTE5Ni4yMjUxJwp2YWx1ZXNldCAiUHN5Y2hvc2lzIjogJ2h0dHA6Ly9jdHMubmxtLm5paC5nb3YvZmhpci9WYWx1ZVNldC8yLjE2Ljg0MC4xLjExMzc2Mi4xLjQuMTE5Ni4zMzQwJwoKdmFsdWVzZXQgIkRlcHJlc3Npb24gTWVkaWNhdGlvbnMiOiAnaHR0cDovL2N0cy5ubG0ubmloLmdvdi9maGlyL1ZhbHVlU2V0LzIuMTYuODQwLjEuMTEzNzYyLjEuNC4xMTk2LjM1MCcKdmFsdWVzZXQgIkFueGlvbHl0aWMgTWVkaWNhdGlvbnMiOiAnaHR0cDovL2N0cy5ubG0ubmloLmdvdi9maGlyL1ZhbHVlU2V0LzIuMTYuODQwLjEuMTEzNzYyLjEuNC4xMTk2LjQ4MDknCnZhbHVlc2V0ICJCaXBvbGFyIERpc29yZGVyIE1lZGljYXRpb25zIjogJ2h0dHA6Ly9jdHMubmxtLm5paC5nb3YvZmhpci9WYWx1ZVNldC8yLjE2Ljg0MC4xLjExMzc2Mi4xLjQuMTE5Ni40ODEwJwp2YWx1ZXNldCAiTW9vZCBTdGFiaWxpemVyIE1lZGljYXRpb25zIjogJ2h0dHA6Ly9jdHMubmxtLm5paC5nb3YvZmhpci9WYWx1ZVNldC8yLjE2Ljg0MC4xLjExMzc2Mi4xLjQuMTE5Ni4zMzQ3JwoKdmFsdWVzZXQgIlNlcnVtIExldmVsIG9mIE1vb2QgU3RhYmlsaXplcnMiOiAnaHR0cDovL2N0cy5ubG0ubmloLmdvdi9maGlyL1ZhbHVlU2V0LzIuMTYuODQwLjEuMTEzNzYyLjEuNC4xMTk2LjQ4NjEnCgovLyB2YWx1ZXNldCAiQmVoYXZvcmlhbCBIZWFsdGggTWVkaWNhdGlvbnMiOiAnaHR0cDovL2hsNy5vcmcvZmhpci91cy9taWhyL1ZhbHVlU2V0L2JlaGF2aW9yYWwtaGVhbHRoLW1lZGljYXRpb25zJwovLyB2YWx1ZXNldCAiQmVoYXZvcmlhbCBIZWFsdGggTWVkaWNhdGlvbnMiOiAnaHR0cDovL2hsNy5vcmcvZmhpci91cy9taWhyL1ZhbHVlU2V0L2h5cGVydGVuc2l2ZS1kaXNvcmRlcnMtcHJlZ25hbmN5JwoKLy8gdmFsdWVzZXQgIkh5cGVydGVuc2l2ZSBEaXNvcmRlcnMgUHJlZ25hbmN5IElDRCI6ICdodHRwOi8vd3d3LmhsNy5vcmcvZmhpci91cy9taWhyL1ZhbHVlU2V0L2h5cGVydGVuc2l2ZS1kaXNvcmRlcnMtcHJlZ25hbmN5LUlDRCcKLy8gdmFsdWVzZXQgIkh5cGVydGVuc2l2ZSBEaXNvcmRlcnMgUHJlZ25hbmN5IFNOT01FRCI6ICdodHRwOi8vd3d3LmhsNy5vcmcvZmhpci91cy9taWhyL1ZhbHVlU2V0L2h5cGVydGVuc2l2ZS1kaXNvcmRlcnMtcHJlZ25hbmN5LVNOT01FRCcKCi8vRGVsaXZlcnkgUHJvY2VkdXJlIEdyb3VwCnZhbHVlc2V0ICJEZWxpdmVyeSBMaXZlIEJpcnRocyI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM4ODMuMy40NjQuMTAwMy4xMTEuMTIuMTAxNScKdmFsdWVzZXQgIkRlbGl2ZXJ5IFByb2NlZHVyZSI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjEwNzguNScKdmFsdWVzZXQgIlByZWduYW5jeSBQcm9jZWR1cmUgRGVsaXZlcnkgQ1BUIjogJ2h0dHA6Ly9obDcub3JnL2ZoaXIvdXMvbWloci9WYWx1ZVNldC9QcmVnbmFuY3lQcm9jZWR1cmVEZWxpdmVyeS1DUFQnCgovL1ByZWduYW5jeSBEZWxpdmVyeSBEaWFnbm9zaXMKdmFsdWVzZXQgIkRlbGl2ZXJ5IERpYWdub3NpcyI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM4ODMuMy42Ny4xLjEwMS4xLjI3OCcKCi8vTm9uLUxpdmUgQmlydGggKEZldGFsIERlYXRoL0Fib3J0aW9uKQp2YWx1ZXNldCAiTm9uIExpdmUgQmlydGggQ1BUIFByb2NlZHVyZXMiOiAnaHR0cDovL2N0cy5ubG0ubmloLmdvdi9maGlyL1ZhbHVlU2V0LzIuMTYuODQwLjEuMTEzNzYyLjEuNC4xMTY2LjEyNycKdmFsdWVzZXQgIk5vbiBMaXZlIEJpcnRoIERpYWdub3NlcyI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjExNjYuMTM3JwoKdmFsdWVzZXQgIkh5cGVydGVuc2lvbiBEdXJpbmcgUHJlZ25hbmN5IjogJ2h0dHA6Ly9jdHMubmxtLm5paC5nb3YvZmhpci9WYWx1ZVNldC8yLjE2Ljg0MC4xLjExMzc2Mi4xLjQuMTE5Ni40ODQzJwp2YWx1ZXNldCAiUG9zdHBhcnR1bSBIeXBlcnRlbnNpb24iOidodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjExOTYuNDgxOCcKdmFsdWVzZXQgIlByZWVjbGFtcHNpYSI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjExOTYuMzQwMycKdmFsdWVzZXQgIkVjbGFtcHNpYSI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjExOTYuNDgyMScKdmFsdWVzZXQgIkdlc3RhdGlvbmFsIERpYWJldGVzIjogJ2h0dHA6Ly9jdHMubmxtLm5paC5nb3YvZmhpci9WYWx1ZVNldC8yLjE2Ljg0MC4xLjExMzc2Mi4xLjQuMTE5Ni40ODE3JwoKdmFsdWVzZXQgIlN1aWNpZGUgSWRlYXRpb24iOiAnaHR0cDovL2N0cy5ubG0ubmloLmdvdi9maGlyL1ZhbHVlU2V0LzIuMTYuODQwLjEuMTEzNzYyLjEuNC4xMTk2LjQyNjUnCnZhbHVlc2V0ICJTdWljaWRlIEF0dGVtcHQiOiAnaHR0cDovL2N0cy5ubG0ubmloLmdvdi9maGlyL1ZhbHVlU2V0LzIuMTYuODQwLjEuMTEzNzYyLjEuNC4xMTk2LjQ4MTQnCnZhbHVlc2V0ICJDb25nZW5pdGFsIEFub21hbGllcyI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjExOTYuNDg0MCcJCnZhbHVlc2V0ICJEZXZlbG9wbWVudGFsIERlbGF5cyI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjExOTYuNDgzNCcKCnZhbHVlc2V0ICJMYWJvciBhbmQgRGVsaXZlcnkgQ29tcGxpY2F0aW9ucyI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjExOTYuNDg2OCcKdmFsdWVzZXQgIlN0aWxsYmlydGgiOiAnaHR0cDovL2N0cy5ubG0ubmloLmdvdi9maGlyL1ZhbHVlU2V0LzIuMTYuODQwLjEuMTEzNzYyLjEuNC4xMTk2LjQ4MjgnCnZhbHVlc2V0ICJQcmVnbmFuY3kgTG9zcyI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjExOTYuNDgyNScKCgp2YWx1ZXNldCAiQW50ZW5hdGFsIFZpc2l0IjogJ2h0dHA6Ly9jdHMubmxtLm5paC5nb3YvZmhpci9WYWx1ZVNldC8yLjE2Ljg0MC4xLjExMzc2Mi4xLjQuMTE5Ni40ODczJwp2YWx1ZXNldCAiUG9zdHBhcnR1bSBWaXNpdCI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjExOTYuNDg1NCcKdmFsdWVzZXQgIlBzeWNoaWF0cnkiOiAnaHR0cDovL2N0cy5ubG0ubmloLmdvdi9maGlyL1ZhbHVlU2V0LzIuMTYuODQwLjEuMTEzNzYyLjEuNC4xMTk2LjQ4NzEnCnZhbHVlc2V0ICJQc3ljaG90aGVyYXB5IFByb2NlZHVyZSI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjExOTYuNDg0NycKdmFsdWVzZXQgIk5JQ1UiOiAnaHR0cDovL2N0cy5ubG0ubmloLmdvdi9maGlyL1ZhbHVlU2V0LzIuMTYuODQwLjEuMTEzNzYyLjEuNC4xMTk2LjQ4NTYnCnZhbHVlc2V0ICJXZWxsIENoaWxkIFZpc2l0IjogJ2h0dHA6Ly9jdHMubmxtLm5paC5nb3YvZmhpci9WYWx1ZVNldC8yLjE2Ljg0MC4xLjExMzc2Mi4xLjQuMTE5Ni40ODYyJwoKdmFsdWVzZXQgIkdlc3RhdGlvbmFsIEFnZSI6ICdodHRwOi8vY3RzLm5sbS5uaWguZ292L2ZoaXIvVmFsdWVTZXQvMi4xNi44NDAuMS4xMTM3NjIuMS40LjExOTYuNDg1NScKCi8qCmNvZGUgIkJNSSI6ICczOTE1Ni01JyBmcm9tICJMT0lOQyIKY29kZSAiQmxvb2QgUHJlc3N1cmUiOiAnODUzNTQtOScgZnJvbSAiTE9JTkMiCmNvZGUgIkhlaWdodCI6ICc4MzAyLTInIGZyb20gIkxPSU5DIgpjb2RlICJCb2R5IFRlbXBlcmF0dXJlIjogJzgzMTAtNScgZnJvbSAiTE9JTkMiCmNvZGUgIkhlYWQgQ2lyY3VtZmVyZW5jZSI6ICc5ODQzLTQnIGZyb20gIkxPSU5DIgpjb2RlICJIZWFydCBSYXRlIjogJzg4NjctNCcgZnJvbSAiTE9JTkMiCmNvZGUgIkxhYm9yYXRvcnkiOiAnbGFib3JhdG9yeScgZnJvbSAiT2JzZXJ2YXRpb24gQ2F0ZWdvcnkiCmNvZGUgIlBlZGlhdHJpYyBCTUkiOiAnNTk1NzYtOScgZnJvbSAiTE9JTkMiCmNvZGUgIkZyb250YWwgSGVhZCBDaXJjdW1mZXJlbmNlIjogJzgyODktMScgZnJvbSAiTE9JTkMiCmNvZGUgIlBlZGlhdHJpYyBXZWlnaHQiOiAnNzc2MDYtMicgZnJvbSAiTE9JTkMiCmNvZGUgIlB1bHNlIE94aW1ldHJ5IjogJzI3MDgtNicgZnJvbSAiTE9JTkMiCmNvZGUgIk94eWdlbiBTYXR1cmF0aW9uIjogJzU5NDA4LTUnIGZyb20gIkxPSU5DIgpjb2RlICJSZXNwaXJhdG9yeSBSYXRlIjogJzkyNzktMScgZnJvbSAiTE9JTkMiCmNvZGUgIlNvY2lhbCBIaXN0b3J5IjogJ3NvY2lhbC1oaXN0b3J5JyBmcm9tICJPYnNlcnZhdGlvbiBDYXRlZ29yeSIKY29kZSAiVml0YWwgU2lnbnMiOiAndml0YWwtc2lnbnMnIGZyb20gIk9ic2VydmF0aW9uIENhdGVnb3J5IgoqLwpjb2RlICJCb2R5IFdlaWdodCI6ICcyOTQ2My03JyBmcm9tICJMT0lOQyIKY29kZSAiRVBEUyI6ICc5OTA0Ni01JyBmcm9tICJMT0lOQyIKY29kZSAiR0FENyI6ICc3MDI3NC02JyBmcm9tICJMT0lOQyIKY29kZSAiUEhROSI6ICc0NDI2MS02JyBmcm9tICJMT0lOQyIKY29kZSAiUEhRMiI6ICc1NTc1OC03JyBmcm9tICJMT0lOQyIKY29kZSAiTTMgRGVwcmVzc2lvbiBTY29yZSI6ICc3MTc1Ny05JyBmcm9tICJMT0lOQyIKY29kZSAiTTMgQW54aWV0eSBTY29yZSI6ICc3MTc1NS0zJyBmcm9tICJMT0lOQyIKY29kZSAiTTMgQmlwb2xhciBTY29yZSI6ICc3MTc1OC03JyBmcm9tICJMT0lOQyIKY29kZSAiTW9vZCBEaXNvcmRlciBRdWVzdGlvbm5haXJlIjogJzg0NzczLTEnIGZyb20gIkxPSU5DIgpjb2RlICJDb25kaXRpb24gQ29uZmlybWVkIFN0YXR1cyI6ICdjb25maXJtZWQnIGZyb20gIkNvbmRpdGlvbiBWZXJpZmljYXRpb24gU3RhdHVzIgoKY29kZSAiTW90aGVyIFJvbGUiOiAnR0VTVE0nIGZyb20gIlJlbGF0aW9uc2hpcFR5cGUiIGRpc3BsYXkgJ0dlc3RhdGlvbmFsIE1vdGhlcicKY29kZSAiTmF0dXJhbCBDaGlsZCI6ICdOQ0hJTEQnIGZyb20gIlJlbGF0aW9uc2hpcFR5cGUiIGRpc3BsYXkgJ05hdHVyYWwgQ2hpbGQnCgpjb2RlICJFbWVyZ2VuY3kgRGVwYXJ0bWVudCBFbmNvdW50ZXIiOiAnRU1FUicgZnJvbSAiRW5jb3VudGVyIENsYXNzIgpjb2RlICJIb3NwaXRhbGl6YXRpb24iOiAnSU1QJyBmcm9tICJFbmNvdW50ZXIgQ2xhc3MiCgpwYXJhbWV0ZXIgIk1lYXN1cmVtZW50IFBlcmlvZCIgSW50ZXJ2YWw8RGF0ZVRpbWU+IGRlZmF1bHQgSW50ZXJ2YWxbQDIwMjEtMDEtMDFUMDA6MDA6MDAuMCwgQDIwMjItMTItMzFUMjM6NTk6NTkuMCkKCmNvbnRleHQgUGF0aWVudAoKZGVmaW5lICJJbml0aWFsIFBvcHVsYXRpb24iOgoJZXhpc3RzKCJCZWhhdmlvcmFsIEhlYWx0aCBEaXNvcmRlcnMgRHVyaW5nIG9yIEFmdGVyIFByZWduYW5jeSIpCglvciAKCWV4aXN0cygiQmVoYXZpb3JhbCBIZWFsdGggTWVkaWNhdGlvbnMgRHVyaW5nIG9yIEFmdGVyIFByZWduYW5jeSIpCglvcgoJIkhhcyBQb3NpdGl2ZSBTY3JlZW5pbmciCgpkZWZpbmUgIlByZWduYW5jeSBFbmRpbmcgaW4gRGVsaXZlcnkiOgoJKCJEZWxpdmVyeSBQcm9jZWR1cmUgR3JvdXAiCgl1bmlvbiAiRGVsaXZlcnkgRGlhZ25vc2lzIEdyb3VwIgoJdW5pb24gIk5vbi1MaXZlIEJpcnRoIEdyb3VwIikgRGVsaXZlcnkKCQl3aGVyZSBDb2FsZXNjZShzdGFydCBvZiBHbG9iYWwuIk5vcm1hbGl6ZSBJbnRlcnZhbCIoRGVsaXZlcnkucGVyZm9ybWVkKSwgRGVsaXZlcnkuYWJhdGVtZW50KQoJCQlkdXJpbmcgIk1lYXN1cmVtZW50IFBlcmlvZCIKCmRlZmluZSAiTGFzdCBEZWxpdmVyeSI6CglMYXN0KCJQcmVnbmFuY3kgRW5kaW5nIGluIERlbGl2ZXJ5IiBECgkJc29ydCBieSBDb2FsZXNjZShzdGFydCBvZiBHbG9iYWwuIk5vcm1hbGl6ZSBJbnRlcnZhbCIocGVyZm9ybWVkKSwgYWJhdGVtZW50KSBhc2MpCgpkZWZpbmUgIkRlbGl2ZXJ5IERhdGUiOgoJQ29hbGVzY2Uoc3RhcnQgb2YgR2xvYmFsLiJOb3JtYWxpemUgSW50ZXJ2YWwiKCJMYXN0IERlbGl2ZXJ5Ii5wZXJmb3JtZWQpLCAiTGFzdCBEZWxpdmVyeSIuYWJhdGVtZW50KQoKZGVmaW5lICJQYXRpZW50IENvbmRpdGlvbnMgZHVyaW5nIG9yIGFmdGVyIFByZWduYW5jeSI6CglbQ29uZGl0aW9uXSBQYXRpZW50Q29uZGl0aW9ucwoJCXdoZXJlIChQYXRpZW50Q29uZGl0aW9ucy5vbnNldCBkdXJpbmcgSW50ZXJ2YWwoCgkJCQkiRGVsaXZlcnkgRGF0ZSIgLSA5IG1vbnRocywKCQkJCSJEZWxpdmVyeSBEYXRlIiArIDEyIG1vbnRocwoJCQkpCgkJCWFuZCBQYXRpZW50Q29uZGl0aW9ucy52ZXJpZmljYXRpb25TdGF0dXMgfiAiQ29uZGl0aW9uIENvbmZpcm1lZCBTdGF0dXMiCgkJKQoKZGVmaW5lICJBbnhpZXR5IER1cmluZyBvciBBZnRlciBQcmVnbmFuY3kiOgoJIlBhdGllbnQgQ29uZGl0aW9ucyBkdXJpbmcgb3IgYWZ0ZXIgUHJlZ25hbmN5IiBDCgkJd2hlcmUgQy5jb2RlIGluICJBbnhpZXR5IgoKZGVmaW5lICJCaXBvbGFyIERpc29yZGVyIER1cmluZyBvciBBZnRlciBQcmVnbmFuY3kiOgoJIlBhdGllbnQgQ29uZGl0aW9ucyBkdXJpbmcgb3IgYWZ0ZXIgUHJlZ25hbmN5IiBDCgkJd2hlcmUgQy5jb2RlIGluICJCaXBvbGFyIERpc29yZGVyIgoKZGVmaW5lICJEZXByZXNzaW9uIER1cmluZyBvciBBZnRlciBQcmVnbmFuY3kiOgoJIlBhdGllbnQgQ29uZGl0aW9ucyBkdXJpbmcgb3IgYWZ0ZXIgUHJlZ25hbmN5IiBDCgkJd2hlcmUgQy5jb2RlIGluICJEZXByZXNzaW9uIgoKZGVmaW5lICJQc3ljaG9zaXMgRHVyaW5nIG9yIEFmdGVyIFByZWduYW5jeSI6CgkiUGF0aWVudCBDb25kaXRpb25zIGR1cmluZyBvciBhZnRlciBQcmVnbmFuY3kiIEMKCQl3aGVyZSBDLmNvZGUgaW4gIlBzeWNob3NpcyIKCmRlZmluZSAiQmVoYXZpb3JhbCBIZWFsdGggRGlzb3JkZXJzIER1cmluZyBvciBBZnRlciBQcmVnbmFuY3kiOgoJCSJBbnhpZXR5IER1cmluZyBvciBBZnRlciBQcmVnbmFuY3kiIHVuaW9uCgkJIkJpcG9sYXIgRGlzb3JkZXIgRHVyaW5nIG9yIEFmdGVyIFByZWduYW5jeSIgdW5pb24KCQkiRGVwcmVzc2lvbiBEdXJpbmcgb3IgQWZ0ZXIgUHJlZ25hbmN5Igl1bmlvbgoJCSJQc3ljaG9zaXMgRHVyaW5nIG9yIEFmdGVyIFByZWduYW5jeSIKCmRlZmluZSAiTWVkaWNhdGlvblJlcXVlc3RzIER1cmluZyBvciBBZnRlciBQcmVnbmFuY3kiOgoJW01lZGljYXRpb25SZXF1ZXN0XSBNZWRpY2F0aW9uUmVxdWVzdHNEdXJpbmdPckFmdGVyUHJlZ25hbmN5Cgl3aGVyZSAoTWVkaWNhdGlvblJlcXVlc3RzRHVyaW5nT3JBZnRlclByZWduYW5jeS5hdXRob3JlZE9uCgkJCWR1cmluZyBJbnRlcnZhbCgKCQkJCSJEZWxpdmVyeSBEYXRlIiAtIDkgbW9udGhzLAoJCQkJIkRlbGl2ZXJ5IERhdGUiICsgMTIgbW9udGhzCgkJCSkKCQkpCgpkZWZpbmUgIkRlcHJlc3Npb24gTWVkaWNhdGlvbnMgRHVyaW5nIG9yIEFmdGVyIFByZWduYW5jeSI6CgkiTWVkaWNhdGlvblJlcXVlc3RzIER1cmluZyBvciBBZnRlciBQcmVnbmFuY3kiIE1SCgkJd2hlcmUgTVIubWVkaWNhdGlvbiBpbiAiRGVwcmVzc2lvbiBNZWRpY2F0aW9ucyIKCmRlZmluZSAiQW54aW9seXRpYyBNZWRpY2F0aW9ucyBEdXJpbmcgb3IgQWZ0ZXIgUHJlZ25hbmN5IjoKCSJNZWRpY2F0aW9uUmVxdWVzdHMgRHVyaW5nIG9yIEFmdGVyIFByZWduYW5jeSIgTVIKCQl3aGVyZSBNUi5tZWRpY2F0aW9uIGluICJBbnhpb2x5dGljIE1lZGljYXRpb25zIgpkZWZpbmUgIkJpcG9sYXIgRGlzb3JkZXIgTWVkaWNhdGlvbnMgRHVyaW5nIG9yIEFmdGVyIFByZWduYW5jeSI6CgkiTWVkaWNhdGlvblJlcXVlc3RzIER1cmluZyBvciBBZnRlciBQcmVnbmFuY3kiIE1SCgkJd2hlcmUgTVIubWVkaWNhdGlvbiBpbiAiQmlwb2xhciBEaXNvcmRlciBNZWRpY2F0aW9ucyIKCmRlZmluZSAiTW9vZCBTdGFiaWxpemVyIE1lZGljYXRpb25zIER1cmluZyBvciBBZnRlciBQcmVnbmFuY3kiOgoJIk1lZGljYXRpb25SZXF1ZXN0cyBEdXJpbmcgb3IgQWZ0ZXIgUHJlZ25hbmN5IiBNUgoJCXdoZXJlIE1SLm1lZGljYXRpb24gaW4gIk1vb2QgU3RhYmlsaXplciBNZWRpY2F0aW9ucyIKCmRlZmluZSAiQmVoYXZpb3JhbCBIZWFsdGggTWVkaWNhdGlvbnMgRHVyaW5nIG9yIEFmdGVyIFByZWduYW5jeSI6CgkJIkRlcHJlc3Npb24gTWVkaWNhdGlvbnMgRHVyaW5nIG9yIEFmdGVyIFByZWduYW5jeSIgdW5pb24KCQkiQW54aW9seXRpYyBNZWRpY2F0aW9ucyBEdXJpbmcgb3IgQWZ0ZXIgUHJlZ25hbmN5IiB1bmlvbgoJCSJCaXBvbGFyIERpc29yZGVyIE1lZGljYXRpb25zIER1cmluZyBvciBBZnRlciBQcmVnbmFuY3kiIHVuaW9uCgkJIk1vb2QgU3RhYmlsaXplciBNZWRpY2F0aW9ucyBEdXJpbmcgb3IgQWZ0ZXIgUHJlZ25hbmN5IgoKLy8gc2luY2UgdGhpcyBpcyBhIHBvc3RuYXRhbCBzY2FsZSwgd2UncmUgbm90IGluY2x1ZGluZyB0aGUgcHJlbmF0YWwgcGVyaW9kIGhlcmUKZGVmaW5lICJFZGluYnVyZ2ggUG9zdG5hdGFsIERlcHJlc3Npb24gU2NhbGUgKEVQRFMpIFNjcmVlbmluZyA+IDEwIjoKCVtPYnNlcnZhdGlvbjogY29kZSB+ICJFUERTIl0gRVBEU2NyZWVuaW5nCgl3aGVyZSAoRVBEU2NyZWVuaW5nLmVmZmVjdGl2ZSAKCQkJZHVyaW5nIEludGVydmFsKAoJCQkJIkRlbGl2ZXJ5IERhdGUiLAoJCQkJIkRlbGl2ZXJ5IERhdGUiICsgMTIgbW9udGhzCgkJCSkKCQlhbmQgKEVQRFNjcmVlbmluZy52YWx1ZSBpcyBub3QgbnVsbAoJCQlhbmQgRVBEU2NyZWVuaW5nLnZhbHVlIGFzIGludGVnZXIgPiAxMCkKCSkKCmRlZmluZSAiR0FELTcgQW54aWV0eSBTY3JlZW5pbmcgPiA4IjoKCVtPYnNlcnZhdGlvbjogY29kZSB+ICJHQUQ3Il0gR0FEN1NjcmVlbmluZwoJd2hlcmUgKEdBRDdTY3JlZW5pbmcuZWZmZWN0aXZlIAoJCQlkdXJpbmcgSW50ZXJ2YWwoCgkJCQkiRGVsaXZlcnkgRGF0ZSIgLSA5IG1vbnRocywKCQkJCSJEZWxpdmVyeSBEYXRlIiArIDEyIG1vbnRocwoJCQkpCgkJYW5kIChHQUQ3U2NyZWVuaW5nLnZhbHVlIGlzIG5vdCBudWxsCgkJCWFuZCBHQUQ3U2NyZWVuaW5nLnZhbHVlIGFzIGludGVnZXIgPiA4KQoJKQpkZWZpbmUgIk1EUSBTY29yZSA+IDciOgoJW09ic2VydmF0aW9uOiBjb2RlIH4gIk1vb2QgRGlzb3JkZXIgUXVlc3Rpb25uYWlyZSJdIE1EUVNjcmVlbmluZwoJd2hlcmUgKE1EUVNjcmVlbmluZy5lZmZlY3RpdmUgCgkJCWR1cmluZyBJbnRlcnZhbCgKCQkJCSJEZWxpdmVyeSBEYXRlIiAtIDkgbW9udGhzLAoJCQkJIkRlbGl2ZXJ5IERhdGUiICsgMTIgbW9udGhzCgkJCSkKCQlhbmQgKE1EUVNjcmVlbmluZy52YWx1ZSBpcyBub3QgbnVsbAoJCQlhbmQgTURRU2NyZWVuaW5nLnZhbHVlIGFzIGludGVnZXIgPiA3KQoJKQoKZGVmaW5lICJQSFE5IFNjb3JlID4gOSI6CglbT2JzZXJ2YXRpb246IGNvZGUgfiAiUEhROSJdIFBIUTlTY3JlZW5pbmcKCXdoZXJlIChQSFE5U2NyZWVuaW5nLmVmZmVjdGl2ZSAKCQkJZHVyaW5nIEludGVydmFsKAoJCQkJIkRlbGl2ZXJ5IERhdGUiIC0gOSBtb250aHMsCgkJCQkiRGVsaXZlcnkgRGF0ZSIgKyAxMiBtb250aHMKCQkJKQoJCWFuZCAoUEhROVNjcmVlbmluZy52YWx1ZSBpcyBub3QgbnVsbAoJCQlhbmQgUEhROVNjcmVlbmluZy52YWx1ZSBhcyBpbnRlZ2VyID4gOSkKCSkKCmRlZmluZSAiSGFzIFBvc2l0aXZlIFNjcmVlbmluZyI6CglleGlzdHMoIkVkaW5idXJnaCBQb3N0bmF0YWwgRGVwcmVzc2lvbiBTY2FsZSAoRVBEUykgU2NyZWVuaW5nID4gMTAiKQoJb3IKCWV4aXN0cygiR0FELTcgQW54aWV0eSBTY3JlZW5pbmcgPiA4IikKCW9yCglleGlzdHMoIk1EUSBTY29yZSA+IDciKQoJb3IgCglleGlzdHMoIlBIUTkgU2NvcmUgPiA5IikKCmRlZmluZSAiRGVsaXZlcnkgUHJvY2VkdXJlIEdyb3VwIjoKCVtQcm9jZWR1cmU6ICJEZWxpdmVyeSBMaXZlIEJpcnRocyJdCgl1bmlvbiBbUHJvY2VkdXJlOiAiRGVsaXZlcnkgUHJvY2VkdXJlIl0KCXVuaW9uIFtQcm9jZWR1cmU6ICJQcmVnbmFuY3kgUHJvY2VkdXJlIERlbGl2ZXJ5IENQVCJdCgpkZWZpbmUgIkRlbGl2ZXJ5IERpYWdub3NpcyBHcm91cCI6CglbQ29uZGl0aW9uOiAiRGVsaXZlcnkgRGlhZ25vc2lzIl0KCXVuaW9uIFtDb25kaXRpb246ICJEZWxpdmVyeSBMaXZlIEJpcnRocyJdCgl1bmlvbiBbQ29uZGl0aW9uOiAiRGVsaXZlcnkgUHJvY2VkdXJlIl0KCXVuaW9uIFtDb25kaXRpb246ICJQcmVnbmFuY3kgUHJvY2VkdXJlIERlbGl2ZXJ5IENQVCJdCgpkZWZpbmUgIk5vbi1MaXZlIEJpcnRoIEdyb3VwIjoKCVtDb25kaXRpb246ICJOb24gTGl2ZSBCaXJ0aCBDUFQgUHJvY2VkdXJlcyJdCgl1bmlvbiBbQ29uZGl0aW9uOiAiTm9uIExpdmUgQmlydGggRGlhZ25vc2VzIl0KCgovLyBhZGQgc3VwcGxlbWVudGFsIGRhdGEgZWxlbWVudHMgZnJvbSB0aGUgbW9tJ3MgcmVjb3JkCQpkZWZpbmUgIlNERSBQYXRpZW50IjoKCVtQYXRpZW50XSBwCgpkZWZpbmUgIlNERSBJbnN1cmFuY2UgQ292ZXJhZ2UiOgoJW0NvdmVyYWdlXSBjCgkgIHdoZXJlIGMucGVyaW9kIG92ZXJsYXBzICJNZWFzdXJlbWVudCBQZXJpb2QiCgpkZWZpbmUgIlNERSBCZWhhdmlvcmFsIEhlYWx0aCBEaXNvcmRlcnMgRHVyaW5nIG9yIEFmdGVyIFByZWduYW5jeSI6CgkiQmVoYXZpb3JhbCBIZWFsdGggRGlzb3JkZXJzIER1cmluZyBvciBBZnRlciBQcmVnbmFuY3kiCgpkZWZpbmUgIlNERSBCZWhhdmlvcmFsIEhlYWx0aCBNZWRpY2F0aW9ucyBEdXJpbmcgb3IgQWZ0ZXIgUHJlZ25hbmN5IjoKCSJCZWhhdmlvcmFsIEhlYWx0aCBNZWRpY2F0aW9ucyBEdXJpbmcgb3IgQWZ0ZXIgUHJlZ25hbmN5IgoKZGVmaW5lICJTREUgSHlwZXJ0ZW5zaW9uIER1cmluZyBQcmVnbmFuY3kiOgoJIlBhdGllbnQgQ29uZGl0aW9ucyBkdXJpbmcgb3IgYWZ0ZXIgUHJlZ25hbmN5IiBDCgkJd2hlcmUgQy5jb2RlIGluICJIeXBlcnRlbnNpb24gRHVyaW5nIFByZWduYW5jeSIKCmRlZmluZSAiU0RFIFByZWNsYW1wc2lhIjoKCSJQYXRpZW50IENvbmRpdGlvbnMgZHVyaW5nIG9yIGFmdGVyIFByZWduYW5jeSIgQwoJCXdoZXJlIEMuY29kZSBpbiAiUHJlZWNsYW1wc2lhIgoKZGVmaW5lICJTREUgRWNsYW1wc2lhIjoKCSJQYXRpZW50IENvbmRpdGlvbnMgZHVyaW5nIG9yIGFmdGVyIFByZWduYW5jeSIgQwoJCXdoZXJlIEMuY29kZSBpbiAiRWNsYW1wc2lhIgoKZGVmaW5lICJTREUgR2VzdGF0aW9uYWwgRGlhYmV0ZXMiOgoJIlBhdGllbnQgQ29uZGl0aW9ucyBkdXJpbmcgb3IgYWZ0ZXIgUHJlZ25hbmN5IiBDCgkJd2hlcmUgQy5jb2RlIGluICJHZXN0YXRpb25hbCBEaWFiZXRlcyIKCmRlZmluZSAiU0RFIFBvc3RwYXJ0dW0gSHlwZXJ0ZW5zaW9uIjoKCSJQYXRpZW50IENvbmRpdGlvbnMgZHVyaW5nIG9yIGFmdGVyIFByZWduYW5jeSIgQwoJCXdoZXJlIEMuY29kZSBpbiAiUG9zdHBhcnR1bSBIeXBlcnRlbnNpb24iCgpkZWZpbmUgIlNERSBTdWljaWRlIElkZWF0aW9uIjoKCSJQYXRpZW50IENvbmRpdGlvbnMgZHVyaW5nIG9yIGFmdGVyIFByZWduYW5jeSIgQwoJCXdoZXJlIEMuY29kZSBpbiAiU3VpY2lkZSBJZGVhdGlvbiIKCmRlZmluZSAiU0RFIFN1aWNpZGUgQXR0ZW1wdCI6CgkiUGF0aWVudCBDb25kaXRpb25zIGR1cmluZyBvciBhZnRlciBQcmVnbmFuY3kiIEMKCQl3aGVyZSBDLmNvZGUgaW4gIlN1aWNpZGUgQXR0ZW1wdCIKCmRlZmluZSAiU0RFIFN0aWxsYmlydGgiOgoJIlBhdGllbnQgQ29uZGl0aW9ucyBkdXJpbmcgb3IgYWZ0ZXIgUHJlZ25hbmN5IiBDCgkJd2hlcmUgQy5jb2RlIGluICJTdGlsbGJpcnRoIgoKZGVmaW5lICJTREUgUHJlZ25hbmN5IExvc3MiOgoJIlBhdGllbnQgQ29uZGl0aW9ucyBkdXJpbmcgb3IgYWZ0ZXIgUHJlZ25hbmN5IiBDCgkJd2hlcmUgQy5jb2RlIGluICJQcmVnbmFuY3kgTG9zcyIKCmRlZmluZSAiU0RFIExhYm9yIGFuZCBEZWxpdmVyeSBDb21wbGljYXRpb25zIjoKCSJQYXRpZW50IENvbmRpdGlvbnMgZHVyaW5nIG9yIGFmdGVyIFByZWduYW5jeSIgQwoJCXdoZXJlIEMuY29kZSBpbiAiTGFib3IgYW5kIERlbGl2ZXJ5IENvbXBsaWNhdGlvbnMiCgpkZWZpbmUgIlNERSBBbnRlbmF0YWwgRW5jb3VudGVyIjoKCVtFbmNvdW50ZXI6IHR5cGUgaW4gIkFudGVuYXRhbCBWaXNpdCJdIEUKCQl3aGVyZSAoRS5wZXJpb2QgIGR1cmluZyBJbnRlcnZhbCgKCQkJCSJEZWxpdmVyeSBEYXRlIiAtIDkgbW9udGhzLAoJCQkJIkRlbGl2ZXJ5IERhdGUiCgkJCSkKCQkpCgpkZWZpbmUgIlNERSBFbWVyZ2VuY3kgRGVwYXJ0bWVudCBFbmNvdW50ZXIiOgoJW0VuY291bnRlcl0gRQoJCXdoZXJlICgKCQkJRS5jbGFzcyB+ICJFbWVyZ2VuY3kgRGVwYXJ0bWVudCBFbmNvdW50ZXIiCgkJCWFuZAoJCQlFLnBlcmlvZCAgZHVyaW5nIEludGVydmFsKAoJCQkJIkRlbGl2ZXJ5IERhdGUiIC0gOSBtb250aHMsCgkJCQkiRGVsaXZlcnkgRGF0ZSIgKyAxMiBtb250aHMKCQkJKQoJCSkKCmRlZmluZSAiU0RFIFBzeWNoaWF0cmljIEhvc3BpdGFsaXphdGlvbiI6CglbRW5jb3VudGVyOiB0eXBlIGluICJQc3ljaGlhdHJ5Il0gRQoJCXdoZXJlICgKCQkJRS5jbGFzcyB+ICJIb3NwaXRhbGl6YXRpb24iCgkJCWFuZAoJCQlFLnBlcmlvZCAgZHVyaW5nIEludGVydmFsKAoJCQkJIkRlbGl2ZXJ5IERhdGUiIC0gOSBtb250aHMsCgkJCQkiRGVsaXZlcnkgRGF0ZSIgKyAxMiBtb250aHMKCQkJKQoJCSkKCmRlZmluZSAiU0RFIFBvc3RwYXJ0dW0gRW5jb3VudGVyIjoKCVtFbmNvdW50ZXI6IHR5cGUgaW4gIlBvc3RwYXJ0dW0gVmlzaXQiXSBFCgkJd2hlcmUgKEUucGVyaW9kICBkdXJpbmcgSW50ZXJ2YWwoCgkJCQkiRGVsaXZlcnkgRGF0ZSIsCgkJCQkiRGVsaXZlcnkgRGF0ZSIgKyAxMiBtb250aHMKCQkJKQoJCSkKCmRlZmluZSAiU0RFIERlbGl2ZXJ5IERhdGUiOgoJIkRlbGl2ZXJ5IERhdGUiCgpkZWZpbmUgIlNERSBBbnRlbmF0YWwgQm9keSBXZWlnaHQiOgoJW09ic2VydmF0aW9uOiBjb2RlIH4gIkJvZHkgV2VpZ2h0Il0JTwoJCXdoZXJlIChPLmVmZmVjdGl2ZSAKCQkJZHVyaW5nIEludGVydmFsKAoJCQkJIkRlbGl2ZXJ5IERhdGUiIC0gOSBtb250aHMsCgkJCQkiRGVsaXZlcnkgRGF0ZSIKCQkJKQoJCSkKCmRlZmluZSAiU0RFIEVkaW5idXJnaCBQb3N0bmF0YWwgRGVwcmVzc2lvbiBTY2FsZSAoRVBEUykgU2NyZWVuaW5nIFNjb3JlcyI6CglbT2JzZXJ2YXRpb246IGNvZGUgfiAiRVBEUyJdIEVQRFNjcmVlbmluZwoJCXdoZXJlIChFUERTY3JlZW5pbmcuZWZmZWN0aXZlIAoJCQlkdXJpbmcgSW50ZXJ2YWwoCgkJCQkiRGVsaXZlcnkgRGF0ZSIsCgkJCQkiRGVsaXZlcnkgRGF0ZSIgKyAxMiBtb250aHMKCQkJKQoJKQoJCQkJCmRlZmluZSAiU0RFIEdBRC03IEFueGlldHkgU2NyZWVuaW5nIFNjb3JlcyI6CglbT2JzZXJ2YXRpb246IGNvZGUgfiAiR0FENyJdIEdBRDdTY3JlZW5pbmcKCXdoZXJlIChHQUQ3U2NyZWVuaW5nLmVmZmVjdGl2ZSAKCQkJZHVyaW5nIEludGVydmFsKAoJCQkJIkRlbGl2ZXJ5IERhdGUiIC0gOSBtb250aHMsCgkJCQkiRGVsaXZlcnkgRGF0ZSIgKyAxMiBtb250aHMKCQkJKQoJKQoKZGVmaW5lICJTREUgTURRIFNjcmVlbmluZyBTY29yZXMiOgoJW09ic2VydmF0aW9uOiBjb2RlIH4gIk1vb2QgRGlzb3JkZXIgUXVlc3Rpb25uYWlyZSJdIE1EUVNjcmVlbmluZwoJd2hlcmUgKE1EUVNjcmVlbmluZy5lZmZlY3RpdmUgCgkJCWR1cmluZyBJbnRlcnZhbCgKCQkJCSJEZWxpdmVyeSBEYXRlIiAtIDkgbW9udGhzLAoJCQkJIkRlbGl2ZXJ5IERhdGUiICsgMTIgbW9udGhzCgkJCSkKCSkKCmRlZmluZSAiU0RFIFBIUTkgU2NyZWVuaW5nIFNjb3JlcyI6CglbT2JzZXJ2YXRpb246IGNvZGUgfiAiUEhROSJdIFBIUTlTY3JlZW5pbmcKCXdoZXJlIChQSFE5U2NyZWVuaW5nLmVmZmVjdGl2ZSAKCQkJZHVyaW5nIEludGVydmFsKAoJCQkJIkRlbGl2ZXJ5IERhdGUiIC0gOSBtb250aHMsCgkJCQkiRGVsaXZlcnkgRGF0ZSIgKyAxMiBtb250aHMKCQkJKQoJKQoKZGVmaW5lICJTREUgUEhRMiBTY3JlZW5pbmcgU2NvcmVzIjoKCVtPYnNlcnZhdGlvbjogY29kZSB+ICJQSFEyIl0gUEhRMlNjcmVlbmluZwoJd2hlcmUgKFBIUTJTY3JlZW5pbmcuZWZmZWN0aXZlIAoJCQlkdXJpbmcgSW50ZXJ2YWwoCgkJCQkiRGVsaXZlcnkgRGF0ZSIgLSA5IG1vbnRocywKCQkJCSJEZWxpdmVyeSBEYXRlIiArIDEyIG1vbnRocwoJCQkpCgkpCgpkZWZpbmUgIlNERSBPYnNlcnZhdGlvbiBTZXJ1bSBMZXZlbCBvZiBNb29kIFN0YWJpbGl6ZXJzIjoKCVtPYnNlcnZhdGlvbjogIlNlcnVtIExldmVsIG9mIE1vb2QgU3RhYmlsaXplcnMiXSBPCgkJd2hlcmUgKE8uc3RhdHVzIGluIHsgJ2ZpbmFsJywgJ2FtZW5kZWQnIH0KCQkJYW5kIE8uZWZmZWN0aXZlIGR1cmluZyBJbnRlcnZhbCgKCQkJCSJEZWxpdmVyeSBEYXRlIiAtIDkgbW9udGhzLAoJCQkJIkRlbGl2ZXJ5IERhdGUiICsgMTIgbW9udGhzCgkJCSkKCQkpCgpkZWZpbmUgIlNERSBPcmRlciBmb3IgUHN5Y2hvdGhlcmFweSI6CglbU2VydmljZVJlcXVlc3Q6ICJQc3ljaG90aGVyYXB5IFByb2NlZHVyZSJdIFAKCQl3aGVyZSAoUC5zdGF0dXMgaW4geyAnY29tcGxldGVkJywgJ2FjdGl2ZScgfQoJCQlhbmQgUC5hdXRob3JlZE9uIGR1cmluZyBJbnRlcnZhbCgKCQkJCQkiRGVsaXZlcnkgRGF0ZSIgLSA5IG1vbnRocywKCQkJCQkiRGVsaXZlcnkgRGF0ZSIgKyAxMiBtb250aHMKCQkJCSkKCQkpCgpkZWZpbmUgIlNERSBQc3ljaG90aGVyYXB5IFByb2NlZHVyZSI6CglbUHJvY2VkdXJlOiAiUHN5Y2hvdGhlcmFweSBQcm9jZWR1cmUiXSBQCgkJd2hlcmUgKFAuc3RhdHVzIGluIHsgJ2NvbXBsZXRlZCcsICdhY3RpdmUnIH0KCQkJYW5kIFAucGVyZm9ybWVkIGR1cmluZyBJbnRlcnZhbCgKCQkJCQkiRGVsaXZlcnkgRGF0ZSIgLSA5IG1vbnRocywKCQkJCQkiRGVsaXZlcnkgRGF0ZSIgKyAxMiBtb250aHMKCQkJCSkKCQkpCQoKLy8gZ2VzdGF0aW9uYWwgYWdlIGFyb3VuZCB0aGUgdGltZSBvZiB0aGUgZGVsaXZlcnkKZGVmaW5lICJTREUgR2VzdGF0aW9uYWwgQWdlIGF0IERlbGl2ZXJ5IjoKCUZpcnN0KFtPYnNlcnZhdGlvbjogIkdlc3RhdGlvbmFsIEFnZSJdIE8KCQl3aGVyZSAoTy5zdGF0dXMgaW4geyAnZmluYWwnLCAnYW1lbmRlZCcgfQoJCQlhbmQgTy5lZmZlY3RpdmUgZHVyaW5nIEludGVydmFsKAoJCQkJIkRlbGl2ZXJ5IERhdGUiIC0gMSBkYXksCgkJCQkiRGVsaXZlcnkgRGF0ZSIgKyAxIGRheQoJCQkpCgkJKQoJCXNvcnQgYnkgZWZmZWN0aXZlIGFzYwoJKQoJCi8vIGxpbmsgdG8gY2hpbGQncyByZWNvcmQKZGVmaW5lICJSZWxhdGVkUGVyc29uIHdobyBpcyB0aGUgQ2hpbGQiOgogIFBhdGllbnQgUAoJbGV0IHJlbGF0ZWRQZXJzb246IChQLmxpbmsgTCB3aGVyZSBGSElSSGVscGVycy5yZXNvbHZlKEwub3RoZXIpIGlzIFJlbGF0ZWRQZXJzb24gcmV0dXJuIEZISVJIZWxwZXJzLnJlc29sdmUoTC5vdGhlcikgYXMgUmVsYXRlZFBlcnNvbikKCXdoZXJlIChyZWxhdGVkUGVyc29uIGlzIG5vdCBudWxsIGFuZCBleGlzdHMocmVsYXRlZFBlcnNvbi5yZWxhdGlvbnNoaXAgUiB3aGVyZSBSIH4gIk1vdGhlciBSb2xlIikpCiAgcmV0dXJuIHJlbGF0ZWRQZXJzb24KCi8vIFRoaXMgZXhwcmVzc2lvbiBoYXMgbm90IGJlZW4gdGVzdGVkIGFzIHRoZSBDUUwgZW5naW5lcyBjdXJyZW50bHkgZG8gbm90IHN1cHBvcnQKLy8gcmVsYXRlZC1jb250dGV4dCByZXRyaWV2ZXMuCi8vIFRoaXMgZGVmaW5pdGlvbiBjaGVja3MgaWYgdGhlIFJlbGF0ZWRQZXJzb24ncyByZWZlcmVuY2VkIHBhdGllbnQgaGFzIGEgYmlydGhEYXRlCi8vIHRoYXQgaXMgZWl0aGVyIG9uZSBkYXkgYmVmb3JlIG9yIG9uZSBkYXkgYWZ0ZXIgdGhlIGRlbGl2ZXJ5IGRhdGUuCi8vIE5vdGU6IElmIFIucGF0aWVudCBpcyBhIHJlZmVyZW5jZSB0byBhIFBhdGllbnQgcmVzb3VyY2UsIGl0IG11c3QgYmUgcmVzb2x2ZWQgdG8gYWNjZXNzIHRoZSBiaXJ0aERhdGUgYXR0cmlidXRlLgpkZWZpbmUgIkNoaWxkIGZyb20gdGhpcyBwcmVnbmFuY3kiOgoJIlJlbGF0ZWRQZXJzb24gd2hvIGlzIHRoZSBDaGlsZCIgUgoJCWxldCBjaGlsZFBhdGllbnQ6IEZISVJIZWxwZXJzLnJlc29sdmUoUi5wYXRpZW50KSBhcyBQYXRpZW50CgkJd2hlcmUgKGNoaWxkUGF0aWVudC5iaXJ0aERhdGUgZHVyaW5nIEludGVydmFsKAoJCQkoZGF0ZSBmcm9tICJEZWxpdmVyeSBEYXRlIikgLSAxIGRheSwKCQkJKGRhdGUgZnJvbSAiRGVsaXZlcnkgRGF0ZSIpICsgMSBkYXkpCgkJKQoJcmV0dXJuIFIKCmRlZmluZSAiU0RFIEluZmFudCBQYXRpZW50IjoKCSJDaGlsZCBmcm9tIHRoaXMgcHJlZ25hbmN5IiBSCglsZXQgY2hpbGRQYXRpZW50OiBGSElSSGVscGVycy5yZXNvbHZlKFIucGF0aWVudCkgYXMgUGF0aWVudAoJcmV0dXJuIGNoaWxkUGF0aWVudAoKZGVmaW5lICJTREUgSW5mYW50IEJvZHkgV2VpZ2h0IGF0IEJpcnRoIjoKCUZpcnN0IChbT2JzZXJ2YXRpb246ICJCb2R5IFdlaWdodCJdIE8KCQkJCXdoZXJlIChPLnN0YXR1cyBpbiB7ICdmaW5hbCcsICdhbWVuZGVkJyB9CgkJCQkJYW5kIE8uZWZmZWN0aXZlIGR1cmluZyBJbnRlcnZhbCgKCQkJCQkJIkRlbGl2ZXJ5IERhdGUiLAoJCQkJCQkiRGVsaXZlcnkgRGF0ZSIgKyAxIGRheQoJCQkJCSkKCQkJCSkKCQkJCXNvcnQgYnkgZWZmZWN0aXZlIGFzYwoJKQoKZGVmaW5lICJTREUgRGlhZ25vc2lzIG9mIENvbmdlbml0YWwgQW5vbWFsaWVzIjoKCVtDb25kaXRpb246ICJDb25nZW5pdGFsIEFub21hbGllcyJdIEMKCQl3aGVyZSAoQy5yZWNvcmRlZERhdGUgZHVyaW5nIEludGVydmFsKAoJCQkJIkRlbGl2ZXJ5IERhdGUiLAoJCQkJIkRlbGl2ZXJ5IERhdGUiICsgMSB5ZWFyCgkJCSkgYW5kCgkJCUMudmVyaWZpY2F0aW9uU3RhdHVzIH4gIkNvbmRpdGlvbiBDb25maXJtZWQgU3RhdHVzIgoJCSkKCmRlZmluZSAiU0RFIERpYWdub3NpcyBvZiBEZXZlbG9wbWVudGFsIERlbGF5cyI6CglbQ29uZGl0aW9uOiAiRGV2ZWxvcG1lbnRhbCBEZWxheXMiXSBDCgkJd2hlcmUgKEMucmVjb3JkZWREYXRlIGR1cmluZyBJbnRlcnZhbCgKCQkJCSJEZWxpdmVyeSBEYXRlIiwKCQkJCSJEZWxpdmVyeSBEYXRlIiArIDEgeWVhcgoJCQkpIGFuZAoJCQlDLnZlcmlmaWNhdGlvblN0YXR1cyB+ICJDb25kaXRpb24gQ29uZmlybWVkIFN0YXR1cyIKCQkpCgoKZGVmaW5lICJTREUgTklDVSBBZG1pc3Npb24iOgoJW0VuY291bnRlcjogdHlwZSBpbiAiTklDVSJdIEUKCXdoZXJlIChFLnBlcmlvZCAgZHVyaW5nIEludGVydmFsKAoJCQkiRGVsaXZlcnkgRGF0ZSIsCgkJCSJEZWxpdmVyeSBEYXRlIiArIDEgeWVhcgoJCSkKCSkKCmRlZmluZSAiU0RFIEluaXRpYWwgV2VsbCBDaGlsZCBWaXNpdCI6CglGaXJzdChbRW5jb3VudGVyOiB0eXBlIGluICJXZWxsIENoaWxkIFZpc2l0Il0gRQoJCXdoZXJlIChFLnBlcmlvZCAgZHVyaW5nIEludGVydmFsKAoJCQkJIkRlbGl2ZXJ5IERhdGUiLAoJCQkJIkRlbGl2ZXJ5IERhdGUiICsgMSB5ZWFyCgkJCSkKCQkpCgkJc29ydCBieSBwZXJpb2Quc3RhcnQgYXNjCgkpCgovKgpkZWZpbmUgIkNoaWxkSGVhZENpcmN1bWZlcmVuY2UiOgogIFsiQ2hpbGQgZnJvbSB0aGlzIHByZWduYW5jeSIgLT4gT2JzZXJ2YXRpb246ICJIZWFkIENpcmN1bWZlcmVuY2UiXSBPCiAgICB3aGVyZSBPLnN0YXR1cyBpbiB7ICdmaW5hbCcsICdhbWVuZGVkJyB9CgpkZWZpbmUgIkxhdGVzdEhlYWRDaXJjdW1mZXJlbmNlIjoKICBMYXN0KAogICAgIkNoaWxkSGVhZENpcmN1bWZlcmVuY2UiIEMKICAgICAgc29ydCBieSBlZmZlY3RpdmUKICApLnZhbHVlIGFzIEZISVIuUXVhbnRpdHkKCiov"